apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: jenkins
  type: LoadBalancer
